module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert('product', [
      {
        name: 'Coca Cola(330ml)',
        product_type: 'cold',
        price: 2.00,
        description: '',
        image: 'images/products/cold_drinks/cola.jpg',
      },
      {
        name: 'Fanta (330ml)',
        product_type: 'cold',
        price: 2.00,
        description: '',
        image: 'images/products/cold_drinks/fanta.jpg',
      },
      {
        name: 'Minute Maid (330ml)',
        product_type: 'cold',
        price: 2.00,
        image: 'images/products/cold_drinks/minute_maid.jpg',
      },
      {
        name: 'Spa Water (500ml)',
        product_type: 'cold',
        price: 1.50,
        description: '',
        image: 'images/products/cold_drinks/water.jpg',
      },
      {
        name: 'Bacardi (50ml)',
        product_type: 'alcohol',
        price: 4.00,
        description: '',
        image: 'images/products/alcoholic_drinks/bacardi.jpg',
      },
      {
        name: 'Gordon Gin (50ml)',
        product_type: 'alcohol',
        price: 4.00,
        description: '',
        image: 'images/products/alcoholic_drinks/gin.jpg',
      },
      {
        name: 'Heineken (500ml)',
        product_type: 'alcohol',
        price: 4.00,
        description: '',
        image: 'images/products/alcoholic_drinks/heineken.jpg',
      },
      {
        name: 'Chardonnay (200ml)',
        product_type: 'alcohol',
        price: 4.00,
        description: '',
        image: 'images/products/alcoholic_drinks/chardonnay.jpg',
      },
      {
        name: 'Merlot (200ml)',
        product_type: 'alcohol',
        price: 4.00,
        description: '',
        image: 'images/products/alcoholic_drinks/merlot.jpg',
      },
      {
        name: 'Chocomel (250ml)',
        product_type: 'cold',
        price: 2.50,
        description: '',
        image: 'images/products/hot_drinks/chocolate.jpg',
      },
      {
        name: 'Koffie',
        product_type: 'hot',
        price: 1.50,
        description: '',
        image: 'images/products/hot_drinks/coffee.jpg',
      },
      {
        name: 'Cup A Soup',
        product_type: 'hot',
        price: 1.50,
        description: '',
        image: 'images/products/hot_drinks/cup_a_soup.jpeg',
      },
      {
        name: 'Thee',
        product_type: 'hot',
        price: 1.50,
        description: '',
        image: 'images/products/hot_drinks/normal_tea.jpg',
      },
      {
        name: '1 Million',
        product_type: 'luxury',
        price: 50,
        description: '',
        image: 'images/products/luxury/1million.png',
      },
      {
        name: 'Armband',
        product_type: 'luxury',
        price: 35,
        description: '',
        image: 'images/products/luxury/armband.jpg',
      },
      {
        name: 'Armband Swarovski set',
        product_type: 'luxury',
        price: 50,
        description: '',
        image: 'images/products/luxury/armband_swarovski.jpg',
      },
      {
        name: 'Coco de Channel',
        product_type: 'luxury',
        price: 50,
        description: '',
        image: 'images/products/luxury/coco.jpg',
      },
      {
        name: 'Gucci zonnebril',
        product_type: 'luxury',
        price: 50,
        description: '',
        image: 'images/products/luxury/zonnebril.png',
      },
      {
        name: 'Rayban zonnebril',
        product_type: 'luxury',
        price: 50,
        description: '',
        image: 'images/products/luxury/rayban.jpg',
      },
      {
        name: 'Loreal Zonnebrand (75ml)',
        product_type: 'luxury',
        price: 10.00,
        description: '',
        image: 'images/products/luxury/sunscreen.jpg',
      },
      {
        name: 'Garnier Zonnebrand kids (75ml)',
        product_type: 'luxury',
        price: 7.00,
        description: '',
        image: 'images/products/luxury/sunscreen_kids.jpg',
      },
      {
        name: 'Kitkat',
        product_type: 'snacks',
        price: 3.00,
        description: '',
        image: 'images/products/snacks/kitkat.png',
      },
      {
        name: 'Lays classic chips',
        product_type: 'snacks',
        price: 1.50,
        description: '',
        image: 'images/products/snacks/chips.jpg',
      },
      {
        name: 'Duyvis pindas',
        product_type: 'snacks',
        price: 1.50,
        description: '',
        image: 'images/products/snacks/pindas.jpeg',
      },
      {
        name: 'M&M (50gram)',
        product_type: 'snacks',
        price: 2.50,
        description: '',
        image: 'images/products/snacks/m&m.jpg',
      },
      {
        name: 'Lays BBQ chips',
        product_type: 'hot_food',
        price: 1.590,
        description: '',
        image: 'images/products/snacks/barbecue_chips.jpeg',
      },
      {
        name: 'Broodje unox',
        product_type: 'hot_food',
        price: 3.00,
        description: '',
        image: 'images/products/warm_food/broodje_unox.jpg',
      },
      {
        name: 'Tosti ham kaas',
        product_type: 'hot_food',
        price: 7,
        description: '',
        image: 'images/products/warm_food/tosti.jpg',
      },
      {
        name: 'Unox noodles',
        product_type: 'hot_food',
        price: 1.50,
        description: '',
        image: 'images/products/warm_food/unox_noodles.jpg',
      },
    ])
  },
  down: (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete('product', null, {});
  }
}
